modLoader="javafml"
loaderVersion="[43,)"
license="MIT"

[[mods]]
modId="workshop_for_handsome_adventurer"
version="${file.jarVersion}"
displayName="Workshop for handsome adventurer"
updateJSONURL="https://raw.githubusercontent.com/moonfather1/workshop_for_handsome_adventurer/main/versions.json"
displayURL="https://modrinth.com/mod/workshop-for-handsome-adventurer"
#logoFile="logo.png"
credits="Big thanks to great guys at forge discord!"
authors="MoonFather"
description='''
Adds a few blocks:
- small worktable like the one from Tinker's Construct
- dual worktable like the one from Gany's Nether mod
- tool rack like one from BiblioCraft or Tetra, etc.
'''

[[dependencies.workshop_for_handsome_adventurer]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.workshop_for_handsome_adventurer]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.19.3)"
    ordering="NONE"
    side="BOTH"

[[dependencies.workshop_for_handsome_adventurer]]
    modId="jade"
    mandatory=false
    versionRange="[5.2.3, )"
    ordering="NONE"
    side="BOTH"

[modproperties.workshop_for_handsome_adventurer]
    catalogueImageIcon="textures/gui/catalogue.png"
    configuredBackground="minecraft:textures/block/spruce_planks.png"
